added Velocity Support
BadlionClient/BadlionClientModAPI pull request #19
Opened 2021-02-24 21:00 UTC by AzraAnimating

Modified the Bungee api's code so it'll work natively with Velocity, left most of the original code in place where possible.

2021-03-05 10:29 UTC, PSNRigner requested changes
Hey, thank your for the PR, that would definitely be interesting to add.

I still need to ask for a second review from my boss to make sure it's all good.

I marked a few details on the PR, unfortunately at Badlion we have a very strict coding style and there are just 2 small lines to change 😉

2021-03-05 10:29 UTC, PSNRigner commented on blcmodapivelocity/src/main/java/net/badlion/blcmodapivelocity/BlcModApiVelocity.java
> +	public void onInitializ(ProxyInitializeEvent event) {
Missing a letter

2021-03-05 10:29 UTC, PSNRigner commented on blcmodapivelocity/src/main/java/net/badlion/blcmodapivelocity/BlcModApiVelocity.java
> +		return server;
Missing `this.`

2021-03-09 21:12 UTC, AzraAnimating commented
Should be fixed :)

2022-01-12 23:56 UTC, PSNRigner commented
Hey, I'm sorry I never looked into it. Will do during the week, we completely remade this plugin recently (see the development branch), we'll add support for Velocity as well 😀

2022-01-13 10:00 UTC, james090500 commented
That'll be amazing!

2022-01-25 14:14 UTC, PSNRigner commented
Velocity support has been added into the upcoming rework of the ModApi. Check the development branch!

2022-01-25 14:14 UTC, closed without merging